config/routes.rb
TokLesesaal::Application.routes.draw do
  resources :media

  root to: 'static_pages#home'

  match '/contact', to: 'static_pages#contact'

end

app/models/medium.rb
class Medium < ActiveRecord::Base
  attr_accessible :autor, :medienart, :schlagwort, :titel, :systematik, :signatur, :isbn, :medienEtikett, :katalogId, :vorhanden

  validates :autor,  	 			     length: { maximum: 120 }
  validates :titel,  	 presence: true, length: { maximum: 140 }
  #validates :isbn,  	 presence: true, length: { maximum: 25 }
  #validates :schlagwort, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  # GET /media
  # GET /media.json
  def index
    #@media = Medium.paginate(page: params[:page])
    @media = Medium.all

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @media }
    #end
  end

  # GET /media/1
  # GET /media/1.json
  def show
    @medium = Medium.find(params[:id])
  end

  # GET /media/new
  # GET /media/new.json
  def new
    @medium = Medium.new
  end

  # GET /media/1/edit
  def edit
    @medium = Medium.find(params[:id])
  end

  # POST /media
  # POST /media.json
  def create
    @medium = Medium.new(params[:medium])

    respond_to do |format|
      if @medium.save
        format.html { redirect_to @medium, notice: 'Medium erfolgreich erstellt.' }
        format.json { render json: @medium, status: :created, location: @medium }
      else
        format.html { render action: "new" }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /media/1
  # PUT /media/1.json
  def update
    @medium = Medium.find(params[:id])

    respond_to do |format|
      if @medium.update_attributes(params[:medium])
        format.html { redirect_to @medium, notice: 'Medium erfolgreich aktualisiert.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium = Medium.find(params[:id])
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to media_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://tat-ort-kollektiv.org/">Tat-Ort-Kollektiv</a>
  </small>
  <nav>
    <ul>
      <!--<li><%= link_to "Contact", contact_path %></li>-->
      <!--<li><a href="http://www.tat-ort.kollektiv.org/">Tat-Ort-Kollektiv e.V.</a></li>-->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "tok lesesaal", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
				
				
	    		</ul>
	 		</nav>
 		</div>
 	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TOK Lesesaal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>	
<div class="container">

<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

<%= yield %>

<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/media/_form.html.erb
<%= form_for(@medium) do |f| %>
  <% if @medium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medium.errors.count, "error") %> prohibited this medium from being saved:</h2>

      <ul>
      <% @medium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :titel %><br />
    <%= f.text_field :titel %>
  </div>
  <div class="field">
    <%= f.label :schlagwort %><br />
    <%= f.text_field :schlagwort %>
  </div>
  <div class="field">
    <%= f.label :vorhanden %><br />
    <%= f.check_box :vorhanden %>
  </div>
  <div class="field">
    <%= f.label :medienEtikett %><br />
    <%= f.text_field :medienEtikett %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media/_medium.html.erb
 <li><%= medium.autor %>
     <%= medium.titel %>
     <%= medium.schlagwort %>
     <%= medium.medienEtikett %>
     <%= medium.systematik %>
     <%= medium.signatur %>
     <%= link_to 'Show', medium %>
     <%= link_to 'Edit', edit_medium_path(medium) %>
     <%= link_to 'Destroy', medium, method: :delete, data: { confirm: 'Sind Sie sicher?' } %>
 </li>

app/views/media/edit.html.erb
<h1>Editing medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<h1>Bücher des TOK</h1>
  <ul class="books">
      <%= render @media %> <!-- partial _medium.html.erb for displaying a single medium -->
  </ul>

<br />
<br />
<%= link_to 'Neues Buch', new_medium_path %>

app/views/media/new.html.erb
<h1>New medium</h1>

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Autor:</b>
  <%= @medium.autor %>
</p>

<p>
  <b>Titel:</b>
  <%= @medium.titel %>
</p>

<p>
  <b>Schlagwort:</b>
  <%= @medium.schlagwort %>
</p>

<p>
  <b>Vorhanden:</b>
  <%= @medium.vorhanden %>
</p>

<p>
  <b>Medienart:</b>
  <%= @medium.medienart %>
</p>


<%= link_to 'Edit', edit_medium_path(@medium) %> |
<%= link_to 'Back', media_path %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Willkommen beim TOK-Lesesaal - UNDER CONSTRUCTION</h1>

	<h2>Hier entsteht der Lesesaal des
  		<a href="http://www.tat-ort.kollektiv.org/">Tat-Ort-Kollektivs e.V.</a>
	</h2>
</div>

<a href="/media">Zum Lesesaal</a>
<br />
<br />
<br />
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>